const REQUEST_INVENTORY = "REQUEST_INVENTORY";
const RECEIVE_INVENTORY = "RECEIVE_INVENTORY";
const REQUEST_FRUIT = "REQUEST_FRUIT";
const RECEIVE_FRUIT = "RECEIVE_FRUIT";
const ADD_FRUIT = "ADD_FRUIT";

export default {
    REQUEST_FRUIT,
    RECEIVE_FRUIT,
    REQUEST_INVENTORY,
    RECEIVE_INVENTORY,
    ADD_FRUIT
}